# Site specific settings
title: "n0tty"
name: "n0ttytalks"
keywords: "Key, words, about, this, website"
baseurl: ""
url: "http://website.com"
description: "Website description"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: 
twitter: TanoyBose
facebook: 
github: n0tty
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
